name: Upload to S3

on:
  push:
    branches:
      - main # or any branch you want

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # ✅ Added session token
          aws-region: ap-south-1 # or your region

      - name: Upload to S3
        run: |
          aws s3 cp . s3://githubautomations3/ --recursive --exclude ".git/*"
